<#
.SYNOPSIS
    Install the NetApp NFS VAAI VIB (NetAppNasPlugin) on ESXi hosts with menu, dry-run, and HTML summary.
.DESCRIPTION
    Connects to vCenter, standalone hosts, a CSV list, or installs from a local path or datastore. Checks
    whether NetAppNasPlugin is already installed on each host before attempting installation via esxcli
    software vib install. Supports dry-run mode and generates an HTML installation summary report.
.NOTES
    Author  : Allen Johnson
    Date    : 2025-07-28
    Version : 1.0
    Module  : VMware.PowerCLI
    Repo    : infra-automation/VMware/ESXi/PowerShell/NFS
    Prereq  : NetApp NAS Plugin VIB pre-staged on a datastore or local path accessible to the target hosts

    NetApp NFS VAAI VIB Installer Script
    Version: 1.0
    Author: Allen Johnson
    Last Updated: 2025-07-28

    Features:
    - Matches against exact VIB name: NetAppNasPlugin
    - Menu options for vCenter, Standalone, CSV
    - Install from Local Path or Datastore
    - Dry-run mode
    - HTML Summary of results
#>

Clear-Host

# === Configuration ===
$DefaultOutputDir = "C:\VAAI_VIB_Install"
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"

# === Helper Functions ===
function Format-HostSummary {
    param ($hostname, $fqdn, $status, $vibPath, $rebootRequired, $duration)
    return "$hostname | $fqdn | $vibPath : $status | Reboot=$rebootRequired ($duration sec)"
}

function Show-Summary {
    param ($summaryArray, $isDryRun)
    $header = if ($isDryRun) { "🧪 DRY-RUN Summary" } else { "📄 VAAI VIB Installation Summary" }
    Write-Host "`n===== $header =====" -ForegroundColor Gray
    foreach ($line in $summaryArray) {
        $hostName, $result = $line -split " : ", 2
        $color = if ($result -like "SUCCESS*") { "Green" }
        elseif ($result -like "ALREADY*") { "Yellow" }
        elseif ($result -like "FAILURE*") { "Red" }
        elseif ($result -like "DRY-RUN*") { "Yellow" }
        else { "Gray" }
        Write-Host "$hostName => $result" -ForegroundColor $color
    }
    Write-Host "`nTotal processed: $($summaryArray.Count)`n" -ForegroundColor White
}

function Export-SummaryToHtml {
    param ($summaryArray, $path, $timestamp, $username)
    $htmlPath = Join-Path $path "vaai_vib_summary_$timestamp.html"

    $html = @()
    $html += "<html><head><meta charset='UTF-8'><style>"
    $html += "body { font-family: Consolas, monospace; background-color: #121212; color: #eee; padding: 1rem; }"
    $html += "table { border-collapse: collapse; width: 100%; margin-top: 1rem; }"
    $html += "th, td { border: 1px solid #555; padding: 6px; text-align: left; }"
    $html += "th { background-color: #1e1e1e; color: #fff; }"
    $html += ".success { color: lightgreen; }"
    $html += ".already { color: khaki; }"
    $html += ".failure { color: salmon; }"
    $html += ".dryrun { color: khaki; }"
    $html += "</style></head><body>"
    $html += "<h2>NetApp NFS VAAI VIB Installation Summary - $timestamp</h2>"
    $html += "<p><strong>Generated by:</strong> $username</p>"
    $html += "<table><tr><th>Host</th><th>FQDN</th><th>VIB Path</th><th>Status</th><th>Reboot Required</th><th>Duration</th></tr>"

    foreach ($line in $summaryArray) {
        if ($line -match "^(?<host>.*?) \| (?<fqdn>.*?) \| (?<vibpath>.*?) : (?<status>.*?) \| Reboot=(?<reboot>.*?) \((?<duration>.*?) sec") {
            $vmHostName = $matches['host']
            $fqdn = $matches['fqdn']
            $vibPath = $matches['vibpath']
            $statusText = $matches['status']
            $reboot = $matches['reboot']
            $duration = $matches['duration'] + " sec"
        }
        else { continue }

        $class = if ($statusText -like "SUCCESS*") { "success" }
        elseif ($statusText -like "ALREADY*") { "already" }
        elseif ($statusText -like "FAILURE*") { "failure" }
        elseif ($statusText -like "DRY-RUN*") { "dryrun" }
        else { "failure" }

        $html += "<tr><td>$vmHostName</td><td>$fqdn</td><td>$vibPath</td><td class='$class'>$statusText</td><td>$reboot</td><td>$duration</td></tr>"
    }

    $html += "</table></body></html>"
    $html | Out-File -FilePath $htmlPath -Encoding UTF8
    Write-Host "📄 HTML summary exported to $htmlPath" -ForegroundColor Yellow
    return $htmlPath
}

# === Menu ===
Write-Host "==========================================" -ForegroundColor Yellow
Write-Host "NetApp NFS VAAI VIB Installer Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Yellow
Write-Host "[1] vCenter (cluster-based or all hosts)"
Write-Host "[2] Standalone ESXi Host(s)"
Write-Host "[3] Import ESXi Hosts from CSV"
Write-Host "[4] Install VAAI VIB from Local Path"
Write-Host "[5] Install VAAI VIB from Datastore"
$selection = Read-Host "Enter selection [1-5]"

# === Dry-run Option ===
$dryRunInput = Read-Host "Enable dry-run mode? (Y/N) [N]"
$dryRun = ($dryRunInput -and $dryRunInput.Trim().ToUpper() -eq "Y")
if ($dryRun) { Write-Host "🧪 DRY-RUN MODE ENABLED" -ForegroundColor Yellow }

# === Output Directory ===
$baseOutputDir = Read-Host "Enter output directory [$DefaultOutputDir]"
if ([string]::IsNullOrWhiteSpace($baseOutputDir)) { $baseOutputDir = $DefaultOutputDir }
New-Item -ItemType Directory -Path $baseOutputDir -Force | Out-Null

$summary = @()
$viCredential = Get-Credential

function Check-And-InstallVIB {
    param ($vmhost, $fqdn, $vibPath)
    $startTime = Get-Date
    $rebootRequired = "No"
    try {
        $vibInstalled = $false
        $vibCheck = Get-EsxCli -VMHost $vmhost -V2
        $vibList = $vibCheck.software.vib.list.Invoke()
        foreach ($vib in $vibList) {
            if ($vib.Name -eq "NetAppNasPlugin") { $vibInstalled = $true }
        }

        if ($dryRun) {
            $summary += Format-HostSummary $vmhost.Name $fqdn "DRY-RUN" $vibPath "No" 0
        }
        elseif ($vibInstalled) {
            $summary += Format-HostSummary $vmhost.Name $fqdn "ALREADY INSTALLED" $vibPath "No" 0
        }
        else {
            Write-Host "Installing NetApp VAAI VIB on $fqdn from $vibPath..." -ForegroundColor Cyan
            $installResult = $vibCheck.software.vib.install.Invoke(@{v=$vibPath; noSigCheck=$true})
            if ($installResult.RebootRequired) { $rebootRequired = "Yes" }
            $duration = [math]::Round((New-TimeSpan -Start $startTime).TotalSeconds, 1)
            $summary += Format-HostSummary $vmhost.Name $fqdn "SUCCESS" $vibPath $rebootRequired $duration
        }
    } catch {
        $duration = [math]::Round((New-TimeSpan -Start $startTime).TotalSeconds, 1)
        $summary += Format-HostSummary $vmhost.Name $fqdn "FAILURE" $vibPath $rebootRequired $duration
    }
}

switch ($selection) {
    "1" {
        $vcenter = Read-Host "Enter vCenter Server name or IP"
        Connect-VIServer -Server $vcenter -Credential $viCredential -ErrorAction Stop
        $clusterName = Read-Host "Enter cluster name (leave blank for all hosts)"
        $VMhosts = if ([string]::IsNullOrWhiteSpace($clusterName)) { Get-VMHost } else { Get-Cluster -Name $clusterName | Get-VMHost }
        $vibPath = Read-Host "Enter VIB Path"
        foreach ($vmhost in $VMhosts) { Check-And-InstallVIB $vmhost $vmhost.Name $vibPath }
    }
    "2" {
        $serverInput = Read-Host "Enter standalone ESXi hostnames/IPs (comma-separated)"
        $vibPath = Read-Host "Enter VIB Path"
        foreach ($esxiHost in ($serverInput -split "," | ForEach-Object { $_.Trim() })) {
            $viSession = Connect-VIServer -Server $esxiHost -Credential $viCredential -ErrorAction Stop
            $VMhostObj = Get-VMHost -Server $viSession
            Check-And-InstallVIB $VMhostObj $esxiHost $vibPath
        }
    }
    "3" {
        $csvPath = Read-Host "Enter path to hosts.csv"
        $csvHosts = Import-Csv $csvPath
        foreach ($row in $csvHosts) {
            $viSession = Connect-VIServer -Server $row.Host -User $row.User -Password $row.Password -ErrorAction Stop
            $VMhostObj = Get-VMHost -Server $viSession
            Check-And-InstallVIB $VMhostObj $row.FQDN $row.VIBPath
        }
    }
    "4" {
        $vibPath = Read-Host "Enter local VIB Path (example: /tmp/NetAppNasPlugin.vib)"
        $serverInput = Read-Host "Enter ESXi hostnames/IPs (comma-separated)"
        foreach ($esxiHost in ($serverInput -split "," | ForEach-Object { $_.Trim() })) {
            $viSession = Connect-VIServer -Server $esxiHost -Credential $viCredential -ErrorAction Stop
            $VMhostObj = Get-VMHost -Server $viSession
            Check-And-InstallVIB $VMhostObj $esxiHost $vibPath
        }
    }
    "5" {
        $datastore = Read-Host "Enter datastore name"
        $vibFile = Read-Host "Enter VIB file name (example: NetAppNasPlugin.vib)"
        $vibPath = "/vmfs/volumes/$datastore/$vibFile"
        $serverInput = Read-Host "Enter ESXi hostnames/IPs (comma-separated)"
        foreach ($esxiHost in ($serverInput -split "," | ForEach-Object { $_.Trim() })) {
            $viSession = Connect-VIServer -Server $esxiHost -Credential $viCredential -ErrorAction Stop
            $VMhostObj = Get-VMHost -Server $viSession
            Check-And-InstallVIB $VMhostObj $esxiHost $vibPath
        }
    }
}

# === Summary ===
Show-Summary -summaryArray $summary -isDryRun:$dryRun
$htmlFile = Export-SummaryToHtml -summaryArray $summary -path $baseOutputDir -timestamp $timestamp -username $viCredential.UserName

$openHtml = Read-Host "Open HTML summary now? (Y/N) [Y]"
if (-not $openHtml -or $openHtml.Trim().ToUpper() -eq "Y") {
    Start-Process $htmlFile
}

Disconnect-VIServer * -Confirm:$false
Write-Host "🔌 Disconnected from all servers." -ForegroundColor Cyan
